[package]
name = "oxide_compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "OxideJS - AST to bytecode compiler"

[dependencies]
oxide_bytecode = { path = "../oxide_bytecode" }
oxide_parser = { path = "../oxide_parser" }
oxide_log = { path = "../oxide_log" }
oxide_dce = { path = "../oxide_dce" }
oxide_cfg = { path = "../oxide_cfg" }
oxide_liveness = { path = "../oxide_liveness" }
oxide_regalloc = { path = "../oxide_regalloc" }
oxide_ir.workspace = true
oxide_emit.workspace = true
serde.workspace = true
serde_json.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
oxide_code_cache = { path = "../oxide_code_cache" }
